
language: objective-c

before_install:

    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:

    - pod lib lint
    - xctool -workspace SDWebImage.xcworkspace -scheme 'SDWebImage' -sdk iphonesimulator clean build
    - xctool -workspace SDWebImage.xcworkspace -scheme 'SDWebImage' -sdk iphoneos clean build
    - xctool -workspace SDWebImage.xcworkspace -scheme 'SDWebImage+WebP' -sdk iphoneos clean build
    - xctool -workspace SDWebImage.xcworkspace -scheme 'SDWebImage+MKAnnotation' -sdk iphoneos clean build

    - xctool -workspace SDWebImage.xcworkspace -scheme 'SDWebImage Demo' clean build

    - cd Tests
    - pod update
    - cd ..
    - xctool -workspace SDWebImage.xcworkspace -scheme 'Tests' clean test